module.exports = [
  {
    // id: 1,
    name: 'Braised Short Ribs o/ white rice',
    // imageUrl: require('../assets/img/brisket-avocado.jpeg'),
    imageUrl:
      'https://lh3.googleusercontent.com/vKU1ddMINiAdWZYrLjeOJ3oEpo_sV3-PKL77h-mCpqq_8XDB0NOPUrdz6UQoNFRYUrjpOlDdyePw-wQaQe5D8bcSdmXuTAcXMX7GJvqpno8rak97O3PqD4nVMHYuNqlXcMWMZVUVMLc0qCptaHndqsI9PpXSrA3LqiSVzLufPc_IwZlSUq0vORsNzNX1vbq4eBOMN7XnOZK8zGY8AqHUWcnGOIlPollc0lFYbM3i3uW2eVtOM-DCimWBvDY3PFZ-aERXlB3o3HHCnaxS3zHfhOHy-yvOfjbpCckOXQgRC7s8wRehqCD9sCPf08cUAfENc4qhuWzDA4ZjKfQsdel_UAJnvOTQFMl6jKiywZpoujeyodleBVOuxq8hjVpVlXJ2XJ0mO14wiwUzvH_KyKiDbmmQoCfQi5GrryQ6QaFle1aziTslELv5T4ygiIgM10_rl5l7lNEWSPAjbw05aDx3peB3tFac9oesM_Rh1R-ioH1iRydwcdsIiiqsFFVLE57EJQXHcsF8pUBsKf7Tk44xgxi8qwFtKvWapURL_ReGlJDX-oMgaKfs0wXSRLm1dtey70zZ2AblEVKAVSiwL6lDSu9_qu9xzx_ABrffUqfGwSUWD8pYxsvGRQFoAUzRaGkNBeE775xDuE0C74Glfkf5FyM2d_SOLIPpd4sv1AxYlBx86E2pmPIxNYQvbspRUg=s1792-no?authuser=0',
    time: '3 hours',
    ingredients: [
      'Short ribs',
      'White Rice',
      'Chipotles in abodo',
      'Onion',
      'Garlic',
      'Avocado',
      'Avocado oil (or any high heat oil)',
      'Cumin',
      'Cayenne',
      'S/P',
    ],
    directions: [
      'Preheat oven to 300F',
      'Add some avocado oil to a dutch oven and get it ripping hot',
      'Place in your short ribs and brown on all sides',
      'Remove the beef and set aside',
      'Add your onion and garlic to the pot',
      'Saute until soft, picking up the fond at the bottom of the pot; add some liquid as needed to do so',
      'Pour in your broth, cover and bring to a simmer',
      'Place your beef into the bath and put the pot covered into the preheated oven',
      'Check on it every hour and remove from oven when the beef easily falls apart',
      'Shred the beef with two forks, remove the bones and enjoy!',
    ],
    userId: 1,
  },
  {
    // id: 2,
    name: 'NY Strip w/ flakey salt',
    // imageUrl: require('../assets/img/steak.jpeg'),
    imageUrl: '',
    time: '20 minutes',
    ingredients: [
      'NY Strip',
      'Avocado oil (or any high heat oil)',
      'Garlic',
      'Butter',
      'Maldon Salt',
      'Pepper',
    ],
    directions: [
      'Get a cast iron pan nice and hot',
      'Rub your steak lightly with high heat oil (make sure your steak is near room temp)',
      'Add the steak to the pan to sear',
      'Continuous flip until internal reads 110F',
      'Kill the heat and add your butter and garlic to the pan',
      'Spoon over the melted butter and garlic continuously for 2 minutes',
      'Remove steak from pan and let rest for 10 minutes',
      'Enjoy!',
    ],
    userId: 1,
  },
  {
    // id: 3,
    name: 'Fried Eggs w/ avocado & sriracha',
    // imageUrl: require('../assets/img/eggs-sriracha.jpeg'),
    time: '10 minutes',
    ingredients: ['Eggs', 'Avocado', 'Sriracha', 'S/P'],
    directions: [
      'Fry your eggs as you like',
      'Cut up an avocado and top when eggs are cooked to your liking',
      'Drizzle your hot sauce',
      'Enjoy!',
    ],
    userId: 1,
  },
  {
    // id: 4,
    name: 'Salmon w/ everything but the bagel',
    // imageUrl: require('../assets/img/salmon-blue.jpeg'),
    time: '10 minutes',
    ingredients: [
      'Wild Salmon',
      'Everything But The Bagel Seasoning',
      'Avocado oil',
    ],
    directions: [
      'Dress your salmon liberally with the seasoning',
      'Sear fillet in hot pan skin side down',
      'Flip after 4 minutes',
      'Reduce heat and cook to desired doneness',
      'Enjoy!',
    ],
    userId: 1,
  },
  {
    // id: 5,
    name: 'Scrambled Eggs w/ bacon',
    // imageUrl: require('../assets/img/eggs-bacon.jpeg'),
    time: '10 minutes',
    ingredients: ['Eggs', 'Thick-cut Bacon', 'Butter', 'S/P'],
    directions: [
      'Preheat oven to 400F',
      'Line a baking sheet with foil and add bacon (be sure not to overlap)',
      'Put the bacon in the oven and cook until crispy (flip as needed)',
      'Add butter to a non-stick pan and get it warm on low heat',
      'Scramble the eggs and add them to the pan',
      'Cook to desired doneness and plate up',
      'Enjoy!',
    ],
    userId: 1,
  },
  {
    // id: 6,
    name: 'Chicken Tikki Masala o/ basmati rice',
    // imageUrl: require('../assets/img/tikka-masala.jpeg'),
    time: '30 minutes',
    ingredients: [
      'Boneless Chicken Thighs',
      'Basmati Rice',
      'Whole Peeled Tomatoes',
      'Coconut Cream',
      'Yellow Onion',
      'Garlic',
      'Fresh Ginger',
      'Cilantro',
      'Coriander',
      'Turmeric',
      'Cumin',
      'Cayenne',
      'Paprika',
      'Black Pepper',
    ],
    directions: [
      'Add your rice to a pot and 1.5x water by weight',
      'Cover and bring to a simmer and immediately reduce heat once simmering',
      'Remove from heat once there is no water left and desired doneness is acheived',
      'Cook your chicken thighs in pan and set aside to let rest',
      'Chop your onions and mince your garlic and fresh ginger',
      'Add them to a hot dutch oven over the stove',
      'Saute for 30 seconds',
      'Add your spices to the pan to bloom for 1 minutes (add more oil as needed)',
      'Add your can of tomatoes to the pot with its liquid and bring to a simmer',
      'Let it simmer for 5-10 minutes to reduce a bit',
      'Add your coconut cream to the pot and stir (dairy works as well)',
      'Dice up your chicken thighs and throw them into the pot',
      'Kill the heat and plate it up',
      'Roughly chop the cilantro and garnish',
      'Enjoy!',
    ],
    userId: 1,
  },
]
